# Use a Node.js base image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the microservice code to the container
COPY . .

# Expose the port on which the microservice will run
EXPOSE 4000

# Run the microservice
CMD [ "node", "index.js" ]
